### ISSUE TITLE
Do releases of app v1 and v2

### ISSUE THREAD

**Issue by ChrisBeeley** [jacgrout/WebinarStats#15]
Tag an old commit before the new app was added with v0.1.0, then go to the latest commit, delete the old files and then do a release of the new version as v0.2.0.

Advisable to use [semantic versioning](https://semver.org/) with subsequent updates

**Comment by jacgrout** [comment]
I've sort of done this but I dont know how to "tag a commit"

**Comment by jacgrout** [comment]
Version 0.2.0 release created. Version 0.1.0 of the app is visible in the archive folder
